package: global_settings
version: '2.8.4'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/global_settings
page:
    title: translate:title
    perm: global_settings[settings] 
    pjax: true
    icon: rex-icon fa-wrench
    subpages:
        settings: { title: 'translate:settings', perm: 'global_settings[settings]' }
        fields: { title: 'translate:fields', perm: 'admin[]' }
        help:
            title: 'translate:help'
            perm: admin[]
            subpages:
                readme: { title: 'translate:help_readme' }
                changelog: { title: 'translate:help_changelog' }
                license: { title: 'translate:help_license' }
requires:
    redaxo: '^5.7'
    php:
        version: '>=7.4'
